apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-student-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: student-1
  project: default
  source:
    repoURL: https://github.com/martaisty/argocd-katas-training.git
    targetRevision: HEAD
    path: quotes-flask/helm/quotes-flask
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true